project:
  type: book

book:
  title: "Stat 416 Statistical Analysis of Time Series"
  author: "Julia Schedler"
  date: "9/23/2024"
  chapters:
    - index.qmd
    - part: Week1.qmd

bibliography: references.bib

format:
  html:
    theme: cosmo
  # pdf:
  #   documentclass: scrreprt

editor: visual

